version: '3.7'

services:
  nodeapp:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: npm start
    expose:
      - 3000
    env_file:
      - .env.prod
      
  nginx-proxy:
    container_name: nginx-proxy
    build:
      context: ./nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - nodeapp