all:
  vars:
    ansible_user: vagrant
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
prod:
  hosts:
    web-app-01: 
       anisble_host: 192.168.50.102
    web-app-02: 
       ansible_host: 192.168.50.103
  vars:
    ansible_password: vagrant
    env: production test
