Vagrant.configure("2") do |config|

  servers=[
    {
      :hostname => "grafana-test2",
      :box => "bento/ubuntu-18.04",
      :ip => "192.168.5.10",
      :ssh_port => '2215'
    },
   {
      :hostname => "grafana-test1",
      :box => "debian/buster64",
      :ip => "192.168.5.11",
      :ssh_port => '2210'
   }
  ]

  servers.each do |machine|

    config.vm.define machine[:hostname] do |node|
      node.vm.box = machine[:box]
      node.vm.hostname = machine[:hostname]
      
      node.vm.network :private_network, ip: machine[:ip]
      node.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: "ssh"

      node.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--memory", 1024]
        v.customize ["modifyvm", :id, "--name", machine[:hostname]]
      end
    end
  end
end
