Vagrant.configure(2) do |config|
    common = <<-SHELL
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh
    docker --version
    sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose
    docker-compose --version
    SHELL

    config.vm.define "testelk1" do |srv11|
        srv11.vm.hostname = "testelk1"
        srv11.vm.box = "bento/ubuntu-18.04"
        srv11.vm.network "private_network", ip: "192.168.70.141"
        srv11.vm.provider "virtualbox" do |v|
            v.customize [ "modifyvm", :id, "--cpus", "1" ]
            v.customize [ "modifyvm", :id, "--memory", "2048" ]
            v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
            v.customize ["modifyvm", :id, "--name", "testelk1"]
        end
        srv11.vm.provision :shell, :inline => common
    end
end