# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  common = <<-SHELL
  
	sudo apt update -y
  	sudo apt install git-flow

  SHELL
  
    config.vm.box = "hashicorp/bionic64"
      
    config.vm.hostname = "mygitflow"
  
    # config.vm.network "private_network", ip: "10.1.1.50"
    config.vm.network "private_network", ip: "192.168.50.10"
  
    config.vm.provision :shell, :inline => common

end

