auditbeat.modules:

- module: auditd
  audit_rules: |
    -w /etc/passwd -p wa -k identity
    -a always,exit -F arch=b32 -S open,creat,truncate,ftruncate,openat,open_by_handle_at -F exit=-EPERM -k access
- module: file_integrity
  paths:
  - /bin
  - /usr/bin
  - /sbin
  - /usr/sbin
  - /etc

- module: system
  datasets:
    - host
    - user
  period: 1m
  user.detect_password_changes: true


# ================================ Processors ===================================
processors:
- add_cloud_metadata: ~


output.elasticsearch:
  hosts: ['elasticsearch:9200']
  username: elastic
  # Read PW from auditbeat.keystore
  password: changepassword

setup.kibana:
  host: "http://kibana:5601"
  username: elastic
  password: changepassword
  dashboards.enabled: true

xpack.monitoring.enabled: true